# Generated by Django 4.0.3 on 2022-03-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='to_do',
            new_name='Todo',
        ),
    ]
